# Generated by Django 6.0.1 on 2026-02-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tech', models.JSONField(default=list)),
                ('difficulty', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
