# Generated by Django 6.0.1 on 2026-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
