# Generated by Django 6.0.1 on 2026-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_primary_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(default='Free', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
