# Generated by Django 6.0.1 on 2026-02-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField()),
                ('skills', models.JSONField(default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('experience_years', models.IntegerField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='mentors/')),
            ],
        ),
        migrations.CreateModel(
            name='MentorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_projects', to='mentors.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('features', models.JSONField(default=list)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='mentors.mentor')),
            ],
        ),
    ]
